---
- name: Install Jenkins+Docker in Ubuntu/Debian
  hosts: jenkins
  gather_facts: 'no'

  become: 'yes'
  tasks:
    - name: Atualizando repositorios do sistema
      command: apt update

    - name: Add Key Jenkins
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Adicionando chaves GPG do Docker ao apt(gerenciador de pacotes)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Instalando aptitude
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Adicionando repositorio do Docker ao apt(gerenciador de pacotes)
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Adicionando repositorio do Jenkins ao apt(gerenciador de pacotes)
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Instalando pacotes necessarios para funcionamento do Docker/Jenkins
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['python3', 'python3-setuptools', 'python3-pip', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'virtualenv', 'openjdk-8-jre
', 'jenkins']

    - name: Instalando docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Instalando modulo python do docker
      pip:
        name:
        - docker
